spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.oauth2.resource.servlet.OAuth2ResourceServerAutoConfiguration
cognito:
  issuer-uri: https://example.com/fake-issuer
cors:
  allowed-origins: http://localhost:3000
productos:
  service:
    url: http://localhost:8081
