import { useEffect, useState } from "react";
import Navbar from "../components/Navbar";
import { apiFetch, getUsuarioActual } from "../services/apiFetch";

const VACIO = { nombre: "", descripcion: "", precio: "", stock: "" };
const dinero = (valor) => new Intl.NumberFormat("es-CL", { style: "currency", currency: "CLP", maximumFractionDigits: 0 }).format(Number(valor) || 0);

export default function Productos() {
  const [productos, setProductos] = useState([]); const [form, setForm] = useState(VACIO); const [esAdmin, setEsAdmin] = useState(false); const [error, setError] = useState(""); const [cargando, setCargando] = useState(true); const [guardando, setGuardando] = useState(false);
  async function cargar() { setCargando(true); setError(""); try { setProductos(await apiFetch("/api/productos")); } catch (e) { setError(e.message); } finally { setCargando(false); } }
  useEffect(() => { cargar(); getUsuarioActual().then((u) => setEsAdmin(u?.grupos?.includes("ADMIN"))); }, []);
  async function crearProducto(e) { e.preventDefault(); setError(""); if (!form.nombre.trim() || !Number.isFinite(Number(form.precio)) || Number(form.precio) <= 0 || !Number.isInteger(Number(form.stock)) || Number(form.stock) < 0) return setError("Revisa los campos: nombre obligatorio, precio mayor que cero y stock entero no negativo."); setGuardando(true); try { await apiFetch("/api/productos", { method: "POST", body: JSON.stringify({ nombre: form.nombre.trim(), descripcion: form.descripcion.trim(), precio: Number(form.precio), stock: Number(form.stock) }) }); setForm(VACIO); await cargar(); } catch (e) { setError(e.message); } finally { setGuardando(false); } }
  async function eliminarProducto(id) { setError(""); try { await apiFetch(`/api/productos/${id}`, { method: "DELETE" }); await cargar(); } catch (e) { setError(e.message); } }
  return <div className="app-shell"><Navbar/><main className="page-wrap"><header className="page-heading"><div><span className="eyebrow">CATÁLOGO · INVENTARIO</span><h1>Productos</h1><p>Consulta precios y existencias disponibles.</p></div><span className="live-indicator">{productos.length} PRODUCTOS</span></header>{error&&<div className="notice notice-error" role="alert">{error}</div>}{esAdmin&&<section className="panel simple-panel" style={{marginTop:26}}><span className="eyebrow">ADMINISTRACIÓN</span><h2>Agregar producto</h2><form className="simple-form" onSubmit={crearProducto}><label className="field"><span>Nombre</span><input placeholder="Nombre del producto" maxLength="100" required value={form.nombre} onChange={e=>setForm({...form,nombre:e.target.value})}/></label><label className="field"><span>Descripción</span><input placeholder="Descripción" maxLength="300" value={form.descripcion} onChange={e=>setForm({...form,descripcion:e.target.value})}/></label><label className="field"><span>Precio</span><input placeholder="0" type="number" min="0" step="1" required value={form.precio} onChange={e=>setForm({...form,precio:e.target.value})}/></label><label className="field"><span>Stock</span><input placeholder="0" type="number" min="0" step="1" required value={form.stock} onChange={e=>setForm({...form,stock:e.target.value})}/></label><button className="button button-primary" disabled={guardando}>{guardando?"Guardando…":"＋ Crear producto"}</button></form></section>}{cargando?<div className="loading-state">Cargando catálogo…</div>:<div className="data-table-wrap" style={{marginTop:25}}><table className="data-table"><thead><tr><th>Producto</th><th>Descripción</th><th>Precio</th><th>Stock</th>{esAdmin&&<th>Acciones</th>}</tr></thead><tbody>{productos.map(p=><tr key={p.id}><td><strong>{p.nombre}</strong><small style={{display:"block",color:"#898880",marginTop:4}}>ID {p.id}</small></td><td>{p.descripcion||"—"}</td><td>{dinero(p.precio)}</td><td><span className={`status-badge ${p.stock>0?"status-confirmado":"status-cancelado"}`}>{p.stock} disponibles</span></td>{esAdmin&&<td><button className="button button-quiet" onClick={()=>eliminarProducto(p.id)}>Eliminar</button></td>}</tr>)}</tbody></table>{productos.length===0&&<div className="loading-state">No hay productos todavía.</div>}</div>}</main></div>;
}
